


WIDTH_VENTANA= 800

HEIGHT_VENTANA = 600

SCALA_PERSONAJE = 0.05

SCALA_BASTON1 = 0.05

SCALA_PODER_BASTON1 = 0.03

FPS = 60

COLOR_FONDO = (0, 0, 0)

VELOCIDAD = 5
VELOCIDAD_PODER = 10   
COOLDOWN_PODER_BASTON1 = 500
ENEMIGOS_BASE        = 4   
ENEMIGOS_POR_OLEADA  = 2


VIDA_ENEMIGO_ESQUELETO        = 50
VELOCIDAD_ENEMIGO_ESQUELETO    = 2
RANGO_ATAQUE_ESQUELETO       = 40
DAÑO_ENEMIGO_ESQUELETO      = 10

VIDA_ENEMIGO_DISTANCIA     = 50
VELOCIDAD_ENEMIGO_DISTANCIA = 1
RANGO_DISPARO_ENEMIGO      = 250
RANGO_HUIDA_ENEMIGO        = 80
COOLDOWN_DISPARO_ENEMIGO   = 1500
VELOCIDAD_PROYECTIL_ENEMIGO = 4
DAÑO_PROYECTIL_ENEMIGO    = 10

RUTA_PROYECTIL_ENEMIGO     = "armas//proyectil_enemigo.png"
SCALA_PROYECTIL_ENEMIGO    = 0.5
RANGO_DETECCION_ENEMIGO = 300
COOLDOWN_ATAQUE_ENEMIGO=300
COOLDOWN_DISPARO_ENEMIGO = 200
DAÑO_BASTON1 = 5