WIDTH_VENTANA= 800

HEIGHT_VENTANA = 600

SCALA_PERSONAJE = 0.05

SCALA_BASTON1 = 0.05

SCALA_PODER_BASTON1 = 0.03

FPS = 60

SCALA_ENEMIGO = 0.15
COLOR_FONDO = (10, 10,30)

VELOCIDAD = 5
VELOCIDAD_PODER = 10   
COOLDOWN_PODER_BASTON1 = 50
ENEMIGOS_BASE        = 6   
ENEMIGOS_POR_OLEADA  = 3


VIDA_ENEMIGO_ESQUELETO        = 75
VELOCIDAD_ENEMIGO_ESQUELETO    = 2
RANGO_ATAQUE_ESQUELETO       = 40
DAÑO_ENEMIGO_ESQUELETO      = 10

VIDA_ENEMIGO_DISTANCIA     = 75
VELOCIDAD_ENEMIGO_DISTANCIA = 2
RANGO_DISPARO_ENEMIGO      = 400
RANGO_HUIDA_ENEMIGO        = 80
VELOCIDAD_PROYECTIL_ENEMIGO = 4
DAÑO_PROYECTIL_ENEMIGO    = 10

RUTA_PROYECTIL_ENEMIGO     = "armas//proyectil_enemigo.png"
SCALA_PROYECTIL_ENEMIGO    = 0.03
RANGO_DETECCION_ENEMIGO = 600
COOLDOWN_ATAQUE_ENEMIGO=300
COOLDOWN_DISPARO_ENEMIGO = 800
DAÑO_BASTON1 = 15
